### ISSUE TITLE
Can't compile with VS 2015 with option -DGSL_SHARED=ON (8 unresolved externals)

### ISSUE THREAD

**Issue by PawelTroka** [ampl/gsl#3]
I just wanted to get dll files. Compilation to *.lib files went just fine, but compilation to shared library failed.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol gsl_sf_legendre_sphPlm_array	gsl	C:\Users\Speedziarz\Downloads\gsl-master\gsl.def	1	
Error	LNK2001	unresolved external symbol gsl_sf_legendre_sphPlm_deriv_array	gsl	C:\Users\Speedziarz\Downloads\gsl-master\gsl.def	1	
Error	LNK2001	unresolved external symbol gsl_sf_legendre_Plm_deriv_array	gsl	C:\Users\Speedziarz\Downloads\gsl-master\gsl.def	1	
Error	LNK2001	unresolved external symbol gsl_sf_legendre_Plm_array	gsl	C:\Users\Speedziarz\Downloads\gsl-master\gsl.def	1	
Error	LNK2001	unresolved external symbol gsl_sf_legendre_array_size	gsl	C:\Users\Speedziarz\Downloads\gsl-master\gsl.def	1	
Error	LNK2001	unresolved external symbol gsl_multifit_fdfsolver_dif_fdf	gsl	C:\Users\Speedziarz\Downloads\gsl-master\gsl.def	1	
Error	LNK2001	unresolved external symbol gsl_bspline_deriv_free	gsl	C:\Users\Speedziarz\Downloads\gsl-master\gsl.def	1	
Error	LNK2001	unresolved external symbol gsl_bspline_deriv_alloc	gsl	C:\Users\Speedziarz\Downloads\gsl-master\gsl.def	1	
Error	LNK1120	8 unresolved externals	gsl	C:\Users\Speedziarz\Downloads\gsl-master\Release\gsl.lib	1	

Another thing is that it would be nice to have an option to compile to x64 too (VS listed only Win32 configuration).

**Comment by vitaut** [comment]
These are deprecated symbols. Defining `GSL_DISABLE_DEPRECATED` to 0 should fix the issue but I don't have VS at hand to check it.

For x64 you just need to specify an appropriate [CMake generator](https://cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html#cmake-generators), e.g.

```
  cmake -G "Visual Studio 11 2012 Win64" ...
```

**Comment by PawelTroka** [comment]
Even with defining GSL_DISABLE_DEPRECATED to 0, it still doesnt compile. Error is the same.

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/gsl/commit/1502fd06ed5f553c02062c5cc81314309fc8fae1. Thanks for reporting.

I've also got rid of `GSL_SHARED` in favor of standard `BUILD_SHARED_LIBS`.
